version: '3'

services:
  my-redis:
    hostname: my-redis
    container_name: my-redis-aof
    image: "redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/conf/redis.conf
    command: redis-server /usr/local/conf/redis.conf